### PR TITLE
Makefile adjustments & simplification

### PR DESCRIPTION
**Pull request by eskultety**
- move the `pip-compile` to a docker image to drop the need to have python 3.9 always installed on the dev machine just to be able to run pip-compile correctly
- simplify the Makefile somewhat as a direct result of the ^above
- drop the `generate-test-data` target

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [n/a] Code coverage from testing does not decrease and new code is covered
- [n/a] Docs updated (if applicable)
- [n/a] Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Comment by eskultety** [comment]
Worth noting that I tested the changes in clean Ubuntu 24.04 and Fedora 40 VMs just to make sure that e.g. Ubuntu doesn't choke on the 'Z' volume permission.

**Review by MartinBasti — APPROVED** [review]

**Review by brunoapimentel — APPROVED** [review]

**Comment by eskultety** [comment]
Reworded the commit messages slightly to remove some obvious typos and stylistic issues.

**Review by MartinBasti — APPROVED** [review]

**Comment by MartinBasti** [comment]
@eskultety FYI, I don't have approval permissions

**Comment by eskultety** [comment]
> @eskultety FYI, I don't have approval permissions

not this again

**Pull request merged**
