### PR TITLE
Store .build-config as YAML in test data

### PR DESCRIPTION
**Pull request by chmeliik**
To make project_files readable, store the expected content of .build-config.json as YAML and configure pyyaml to output nicer multiline strings.

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- N/A Code coverage from testing does not decrease and new code is covered
- N/A Docs updated (if applicable)
- N/A Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Comment by chmeliik** [comment]
Updated with new test cases

**Comment by chmeliik** [comment]
FYI the only non-auto-generated change is in tests/integration/utils.py

**Review by taylormadore — APPROVED** [review]
Such readable. Wow. :rocket:

**Review by brunoapimentel — APPROVED** [review]

**Comment by chmeliik** [comment]
Rebased on master, converted one .build-config

**Pull request merged**
