### PR TITLE
Add integration tests for npm bundled dependencies

### PR DESCRIPTION
**Pull request by chmeliik**
STONEBLD-1409

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [n/a] Docs updated (if applicable)
- [n/a] Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Comment by chmeliik** [comment]
If you want to see what cachi2 does wrong, remove the `xfail` marks

For lockfile v3, cachi2 thinks that bundled dependencies are `file:` dependencies so it properly (but accidentally) skips downloading them, but reports them as file deps in the SBOM.

```
pkg:npm/ansi-regex@2.0.0?vcs_url=git%2Bhttps://github.com/cachito-testing/npm-cachi2-bundled.git%40de68ac6aa88a81272660b6d0f6d44ce157207799#node_modules/bundle-dependencies/node_modules/ansi-regex
```

For lockfile v1, cachi2 thinks they are https dependencies so raises a missing checksum error

```
E         Error: PackageRejected: strip-bom is missing integrity checksum. It is mandatoryfor https dependencies.
E           Please double-check provided package-lock.json that your dependencies specify integrity. Try to rerun `npm install` on your repository.
```

**Comment by chmeliik** [comment]
Filed STONEBLD-1475

**Review by lkolacek — APPROVED** [review]
Looks great :+1:

**Review by ejegrova — APPROVED** [review]
LGTM :+1:

**Pull request merged**
