### PR TITLE
Add gomod vendored integration test without flags

### PR DESCRIPTION
**Pull request by lkolacek**
Test case is supposed to fail without gomod-vendor flags when a repository with vendor directory is provided.

CLOUDBLD-12625

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- n/a New code has type annotations
- n/a Docs updated (if applicable)
- n/a Docs links in the code are still valid (if docs were updated)
- n/a [Issue](https://github.com/containerbuildsystem/cachi2/issues/13) that tracks breaking changes to the OSBS2 integration is updated (if applicable)

### CODE REVIEW

**Comment by lkolacek** [comment]
@brunoapimentel  @chmeliik @taylormadore

This test cases should fail because repo contains vendor dir and vendor flags were not provided to fetch-deps cmd. But since worker config is not set on strict it fetches dependencies successfully. 
* https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/config.py#L19
* https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/package_managers/gomod.py#L441

Do we want to enable this flag?

**Comment by chmeliik** [comment]
> This test cases should fail because repo contains vendor dir and vendor flags were not provided to fetch-deps cmd. But since worker config is not set on strict it fetches dependencies successfully.
> 
>     * https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/config.py#L19
> 
>     * https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/package_managers/gomod.py#L441
> 
> 
> Do we want to enable this flag?

+1

we probably want to change vendor handling as a whole, but enabling strict mode until then doesn't hurt

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Comment by chmeliik** [comment]
Breaking changes issue *would* be relevant, but we've dropped it already

**Comment by brunoapimentel** [comment]
> @brunoapimentel @chmeliik @taylormadore
> 
> This test cases should fail because repo contains vendor dir and vendor flags were not provided to fetch-deps cmd. But since worker config is not set on strict it fetches dependencies successfully.
> 
> * https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/config.py#L19
> * https://github.com/containerbuildsystem/cachi2/blob/main/cachi2/core/package_managers/gomod.py#L441
> 
> Do we want to enable this flag?

Here's where being able to set config options during the CLI invokation would've been useful. 
+1 for enabling it anyway.

**Review by brunoapimentel — APPROVED** [review]

**Pull request merged**
