### PR TITLE
tox.ini: Fix Python environment factors

### PR DESCRIPTION
**Pull request by eskultety**
# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- n/a Code coverage from testing does not decrease and new code is covered
- n/a Docs updated (if applicable)
- n/a Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
A few mentions of `tox -e python3.9` in the README need an update

Otherwise LGTM, thanks for fixing this! 
Side note: _that's_ what a commit message is supposed to look like :tada:

**Comment by eskultety** [comment]
> A few mentions of `tox -e python3.9` in the README need an update

Oops, totally missed that, sorry. Fixed in the revision.

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Review by taylormadore — APPROVED** [review]
LGTM :tada:

**Pull request merged**
