### PR TITLE
yarn: frozen-lockfile integration test

### PR DESCRIPTION
**Pull request by slimreaper35**
# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] Docs updated (if applicable)
- [ ] Docs links in the code are still valid (if docs were updated)

**Note:** if the contribution is external (not from an organization member), the CI
pipeline will not run automatically. After verifying that the CI is safe to run:

- [approve GitHub Actions workflows][approve-gh-actions] by clicking a button
- approve the Red Hat Trusted App Pipeline container build by commenting `/ok-to-test`
  (as is the [standard for Pipelines as Code][pac-running-pipeline])

[approve-gh-actions]: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
[pac-running-pipeline]: https://pipelinesascode.com/docs/guide/running/#running-the-pipelinerun

### CODE REVIEW

**Comment by slimreaper35** [comment]
Related PR: https://github.com/cachito-testing/cachi2-yarn/pull/1

**Comment by eskultety** [comment]
> closes https://github.com/containerbuildsystem/cachi2/issues/655

The way the issue is currently written then this PR definitely doesn't resolve it, it only addresses one of the list items. Depending on the consensus on https://github.com/containerbuildsystem/cachi2/issues/655#issuecomment-2413095298 this PR might eventually be merged as is OR it'll need an additional inverted test (i.e. removing deps).

**Comment by slimreaper35** [comment]
https://github.com/cachito-testing/cachi2-yarn/tree/invalid_frozen_lockfile

When I manually ran the command `yarn install --frozen-lockfile` on that branch lockfile wasn't touched at all.

**Review by eskultety — APPROVED** [review]
Tiny update to the commit message needed, otherwise ACK.

**Review by a-ovchinnikov — APPROVED** [review]

**Pull request merged**
