### PR TITLE
Add gomod integration tests with go generate

### PR DESCRIPTION
**Pull request by lkolacek**
Test case checks if fetching dependencies will not fail if
non-existent package is imported.

CLOUDBLD-12629

Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- n/a New code has type annotations
- n/a Docs updated (if applicable)
- n/a Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Comment by lkolacek** [comment]
PR should be ready for review. I dropped go-generate scenario since it did not provide much value for us. It basically checked if a line in main.go for go generate is ignored and does not affect fetching deps at all. I also added comments to test cases about why and what we test there, please check if it's accurate.

**Comment by chmeliik** [comment]
> PR should be ready for review. I dropped go-generate scenario since it did not provide much value for us. It basically checked if a line in main.go for go generate is ignored and does not affect fetching deps at all. I also added comments to test cases about why and what we test there, please check if it's accurate.

After thinking about it some more, if we assume that the  the go:generate line does not affect Cachi2, the only scenario which really seems unique is [go-generate-imported](https://github.com/cachito-testing/go-generate-imported). It checks that Cachi2 can report packages which don't exist and that Cachi2 doesn't fail (as it possibly would if we didn't list with the `-e` flag).

The question is if we want to verify the go:generate assumption or not.

**Comment by chmeliik** [comment]
> The question is if we want to verify the go:generate assumption or not.

I'm leaning more on the side of not verifying it, if we wanted to test everything that Cachi2 doesn't do we would need infinitely many tests

**Comment by lkolacek** [comment]
My first impression here was also that we test something which is outside of Cachi2 responsibility. But you guys mentioned reasonable points here: [slack_private_channel](https://redhat-internal.slack.com/archives/C02BKU2QJQ0/p1674052206457589?thread_ts=1667908364.851589&cid=C02BKU2QJQ0) so I decided to leave at least these 3 tests. I am OK here to leave only go-generate-imported or even drop them all -> since go generate is the user responsibility.  Other thoughts @brunoapimentel @ejegrova @taylormadore @fepas ?

**Comment by chmeliik** [comment]
We should keep at least the generate-imported one, that one verifies that we don't fail when something imports a non-existent package. I'm OK with dropping the rest

**Comment by brunoapimentel** [comment]
> It checks that Cachi2 can report packages which don't exist and that Cachi2 doesn't fail (as it possibly would if we didn't list with the `-e` flag).

Ack. We should probably make this reasoning clear in the test comments:
> It checks that Cachi2 can report packages which don't exist and that Cachi2 doesn't fail (as it possibly would if we didn't list with the -e flag).

**Comment by lkolacek** [comment]
OK I dropped all test cases except `gomod_go_generate_imported`. Is explanation in comment clear enough or would you add anything there?

**Comment by brunoapimentel** [comment]
> OK I dropped all test cases except `gomod_go_generate_imported`. Is explanation in comment clear enough or would you add anything there?

It's perfect, you're the best :blush:

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

minor nitpick for the commit message which still says it's 4 tests

**Review by brunoapimentel — APPROVED** [review]

**Comment by lkolacek** [comment]
> LGTM +1
> 
> minor nitpick for the commit message which still says it's 4 tests

Good catch. Fixed and merging

**Pull request merged**
