### PR TITLE
Make Yarnberry a successful noop

### PR DESCRIPTION
**Pull request by chmeliik**
# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] Docs updated (if applicable)
- [ ] Docs links in the code are still valid (if docs were updated)

### CODE REVIEW

**Comment by chmeliik** [comment]
Might be worth merging given how simple it is to make things not fail?

test with (save as a file, `git apply` this file)

```diff
diff --git a/cachi2/core/resolver.py b/cachi2/core/resolver.py
index 7bbc8a9..c5492ba 100644
--- a/cachi2/core/resolver.py
+++ b/cachi2/core/resolver.py
@@ -4,7 +4,7 @@ from typing import Callable
 from cachi2.core.errors import UnsupportedFeature
 from cachi2.core.models.input import PackageManagerType, Request
 from cachi2.core.models.output import RequestOutput
-from cachi2.core.package_managers import gomod, npm, pip
+from cachi2.core.package_managers import gomod, npm, pip, yarn
 
 Handler = Callable[[Request], RequestOutput]
 
@@ -14,6 +14,9 @@ _package_managers: dict[PackageManagerType, Handler] = {
     "pip": pip.fetch_pip_source,
 }
 
+_package_managers_under_development: dict[PackageManagerType, Handler] = {
+    "yarn": yarn.fetch_yarn_source
+}
 
 supported_package_managers = list(_package_managers)
 
@@ -21,14 +24,15 @@ supported_package_managers = list(_package_managers)
 def resolve_packages(request: Request) -> RequestOutput:
     """Run all requested package managers, return their combined output."""
     requested_types = set(pkg.type for pkg in request.packages)
-    unsupported_types = requested_types - _package_managers.keys()
+    package_managers = _package_managers | _package_managers_under_development
+    unsupported_types = requested_types - package_managers.keys()
     if unsupported_types:
         raise UnsupportedFeature(
             f"Package manager(s) not yet supported: {', '.join(sorted(unsupported_types))}",
             # unknown package managers shouldn't get past input validation
             solution="But the good news is that we're already working on it!",
         )
-    pkg_managers = [_package_managers[type_] for type_ in sorted(requested_types)]
+    pkg_managers = [package_managers[type_] for type_ in sorted(requested_types)]
     return _merge_outputs(pkg_manager(request) for pkg_manager in pkg_managers)



```

**Review by brunoapimentel — APPROVED** [review]
LGTM!

Better check with @ben-alkov if this does not affect his WIP.

**Comment by chmeliik** [comment]
> LGTM!
> 
> Better check with @ben-alkov if this does not affect his WIP.

I think Ben's work shouldn't need to go deeper than `core.resolver`

This diff certainly could conflict if it was part of the PR. :slightly_smiling_face: https://github.com/containerbuildsystem/cachi2/pull/337#issuecomment-1746530057

**Review by ben-alkov — APPROVED** [review]

**Comment by ben-alkov** [comment]
> > LGTM!
> > Better check with @ben-alkov if this does not affect his WIP.
> 
> I think Ben's work shouldn't need to go deeper than `core.resolver`
> 
> This diff certainly could conflict if it was part of the PR. 🙂 [#337 (comment)](https://github.com/containerbuildsystem/cachi2/pull/337#issuecomment-1746530057)

No worries; I don't have anything ready to PR yet. Also, thanks for the tip about `core.resolver` :grin:

**Pull request merged**
