### PR TITLE
Keep only minimal stub of metadata doc

### PR DESCRIPTION
**Pull request by chmeliik**
CLOUDBLD-11125

There are too many unknowns at this time to make documenting the metadata formats worth the effort.

* Do we want to document the output.json format at all?
  * Would it be relevant for anything except OSBS?
* How will we provide the content manifest?
* Will the content manifest look the same as it does in Cachito?

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] New code has type annotations
- [x] Docs updated (if applicable)

### CODE REVIEW

**Comment by chmeliik** [comment]
What do you think?

I can copy over the relevant parts of [Request JSON](https://github.com/containerbuildsystem/cachito/blob/master/docs/metadata.md#request-json) to document the output.json format if we want that, I would probably just need to replace then yarn+npm example with a gomod example

**Comment by MartinBasti** [comment]
I'd go with minimal doc and file a story for each potentially missing part

**Comment by chmeliik** [comment]
Rebased on main, will add short output.json documentation

**Comment by chmeliik** [comment]
> I can copy over the relevant parts of [Request JSON](https://github.com/containerbuildsystem/cachito/blob/master/docs/metadata.md#request-json) to document the output.json format if we want that, I would probably just need to replace the yarn+npm example with a gomod example

Oh man, gomod is the worst example for this. It breaks all the rules that other package managers follow :angry: 

I copied and updated the npm+yarn based example.

Would you rather:
* keep the examples npm+yarn based and document that we don't support them yet?
* change the example to a gomod one and fix many sections in the doc?

**Review by taylormadore — APPROVED** [review]
LGTM :+1:

**Review by ejegrova — APPROVED** [review]

**Pull request merged**
