### PR TITLE
Add gomod e2e test with multiple modules

### PR DESCRIPTION
**Pull request by chmeliik**
STONEBLD-468

Why an e2e test?
----------------

In this test, we download versions v1.5.1 and v1.5.2 of the rsc.io/quote module. Cachi2 has logic for merging `@v/list` files for dependencies. The list file should, according to our expectations, have the following content:

    v1.5.1
    v1.5.2

This is not the case. The content ends up being only "v1.5.2". But the installation works anyway, so we don't really have to worry about it.

To test that the installation works, we need an e2e test.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] New code has type annotations
- [ ] ~Docs updated (if applicable)~
- [ ] ~Docs links in the code are still valid (if docs were updated)~

### CODE REVIEW

**Comment by chmeliik** [comment]
Mypy depends on #76

**Comment by chmeliik** [comment]
Rebased on main, added sha256: prefixes

**Comment by chmeliik** [comment]
PTAL

This uncovered a bug: golang doesn't leave the `list.lock` file behind anymore, so Cachito doesn't merge the `list` files https://github.com/containerbuildsystem/cachi2/blob/5bc2ea9e5c87058c3608f900f7f699188e178fe7/cachi2/core/package_managers/gomod.py#L682-L686

But I'm not too inclined to fix it, it would just be replacing one hack with another hack. The true fix would be to rework how we handle multiple Go modules (re-use the same download dir for all of them)

**Comment by lkolacek** [comment]
> This is not the case. The content ends up being only "v1.5.2". But the installation works anyway, so we don't really have to worry about it.

Do we want to add comment and simple check for `@v/list` file that the content is only v1.5.2 and should be both v1.5.2
 and v1.5.1 ? I suppose this is fault on go side. Should we report that somewhere?

**Comment by lkolacek** [comment]
> > This is not the case. The content ends up being only "v1.5.2". But the installation works anyway, so we don't really have to worry about it.
> 
> Do we want to add comment and simple check for `@v/list` file that the content is only v1.5.2 and should be both v1.5.2 and v1.5.1 ?

Discussed with Adam and the best would be probably to leave it like this for now and open nice to have ticket for improvement to generate this on go side.

**Comment by chmeliik** [comment]
> Discussed with Adam and the best would be probably to leave it like this for now and open nice to have ticket for improvement to generate this on go side.

:+1: filed STONEBLD-685

> Do we want to add comment and simple check for `@v/list` file that the content is only v1.5.2 and should be both v1.5.2
and v1.5.1 ?

I'm thinking of adding a generic way to check the content of files in the deps/* directories (the main way would still be checksums, but you could manually specify the expected content for some file). I'll draft something up

**Comment by chmeliik** [comment]
Added `fetch_deps_file_contents.yaml`

Similar to `fetch_deps_sha256sums.json`, but checks text content rather than a checksum


Meant to be a completely optional check if you want to verify the text content of some dependency file

**Review by brunoapimentel — APPROVED** [review]
It LGTM :rocket: 
Great catch on the `list.lock` bug.

**Comment by chmeliik** [comment]
> It LGTM rocket Great catch on the `list.lock` bug.

I can't take all the credit, verifying the content of the `list` file was part of the acceptance criteria :smile:

**Review by taylormadore — APPROVED** [review]
LGTM :+1:

**Review by lkolacek — APPROVED** [review]
Looks great! :+1:

**Pull request merged**
